<?php
// DO NOT EDIT THIS FILE. IT WILL BE AUTO-GENERATE ITSELF FROM TIME TO TIME.
require 'partials/auth_route.php';
require 'partials/home_route.php';
require 'partials/investor_route.php';
require 'partials/paytm_route.php';
require 'partials/profile_route.php';
require 'partials/research_route.php';
require 'partials/researcher_route.php';
